/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: ysARRCHV1WjEODfujFx89hSeAeQ4fXvcTaIWL0OJSJTVDkEYUsypI8QMocHv/XLYEwBJMBKK5T7PcoJOSsdEvw==
 */

/* eslint-disable */
// tslint:disable

interface CustomPlans {
  /**
   * @default nextval('custom_plans_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'custom_plans_id'}
  price: string
}
export default CustomPlans;

interface CustomPlans_InsertParameters {
  /**
   * @default nextval('custom_plans_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'custom_plans_id'}
  price: string
}
export type {CustomPlans_InsertParameters}
