/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: UnCuNr3sC252rt1CC/eysABILPmQk8xJZCIM+0Ih5kt4A29FHOFss5c2BAMy5n8nDRo4I8Dmb2uuCZoiIx8Ahg==
 */

/* eslint-disable */
// tslint:disable

import CustomPlans from './custom_plans'
import Features from './features'
import PlanFeatureType from './plan_feature_type'

interface CustomPlanFeature {
  /**
   * @default '2022-06-24'::date
   */
  created_at: Date
  custom_plan_id: (CustomPlans['id']) | null
  feature_id: (Features['id']) | null
  is_active: (boolean) | null
  max_limit: (number) | null
  type_id: (PlanFeatureType['id']) | null
  /**
   * @default '2022-06-24'::date
   */
  updated_at: Date
}
export default CustomPlanFeature;

interface CustomPlanFeature_InsertParameters {
  /**
   * @default '2022-06-24'::date
   */
  created_at?: Date
  custom_plan_id?: (CustomPlans['id']) | null
  feature_id?: (Features['id']) | null
  is_active?: (boolean) | null
  max_limit?: (number) | null
  type_id?: (PlanFeatureType['id']) | null
  /**
   * @default '2022-06-24'::date
   */
  updated_at?: Date
}
export type {CustomPlanFeature_InsertParameters}
