/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: Mr7dNGO7VmtGnui/hdB7QOU1vm57/fomUCM7OfwkqoIJD0qENa1/yPc+25OrayuJhVWSKnY0Z05McYebS/YJJQ==
 */

/* eslint-disable */
// tslint:disable

interface Pgmigrations {
  /**
   * @default nextval('pgmigrations_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'pgmigrations_id'}
  name: string
  run_on: Date
}
export default Pgmigrations;

interface Pgmigrations_InsertParameters {
  /**
   * @default nextval('pgmigrations_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'pgmigrations_id'}
  name: string
  run_on: Date
}
export type {Pgmigrations_InsertParameters}
