SELECT
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'AF' AND name = 'Afghanistan') = NULL THEN 'NOT' ELSE 'OK' END) AS Afghanistan,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'AL' AND name = 'Albania') = NULL THEN 'NOT' ELSE 'OK' END) AS Albania,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'DZ' AND name = 'Algeria') = NULL THEN 'NOT' ELSE 'OK' END) AS Algeria,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'AD' AND name = 'Andorra') = NULL THEN 'NOT' ELSE 'OK' END) AS Andorra,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'AO' AND name = 'Angola') = NULL THEN 'NOT' ELSE 'OK' END) AS Angola,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'AG' AND name = 'Antigua And Barbuda') = NULL THEN 'NOT' ELSE 'OK' END) AS Antigua And Barbuda,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'AR' AND name = 'Argentina') = NULL THEN 'NOT' ELSE 'OK' END) AS Argentina,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'AM' AND name = 'Armenia') = NULL THEN 'NOT' ELSE 'OK' END) AS Armenia,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'AU' AND name = 'Australia') = NULL THEN 'NOT' ELSE 'OK' END) AS Australia,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'AT' AND name = 'Austria') = NULL THEN 'NOT' ELSE 'OK' END) AS Austria,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'AZ' AND name = 'Azerbaijan') = NULL THEN 'NOT' ELSE 'OK' END) AS Azerbaijan,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'BH' AND name = 'Bahrain') = NULL THEN 'NOT' ELSE 'OK' END) AS Bahrain,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'BD' AND name = 'Bangladesh') = NULL THEN 'NOT' ELSE 'OK' END) AS Bangladesh,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'BB' AND name = 'Barbados') = NULL THEN 'NOT' ELSE 'OK' END) AS Barbados,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'BY' AND name = 'Belarus') = NULL THEN 'NOT' ELSE 'OK' END) AS Belarus,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'BE' AND name = 'Belgium') = NULL THEN 'NOT' ELSE 'OK' END) AS Belgium,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'BZ' AND name = 'Belize') = NULL THEN 'NOT' ELSE 'OK' END) AS Belize,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'BJ' AND name = 'Benin') = NULL THEN 'NOT' ELSE 'OK' END) AS Benin,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'BM' AND name = 'Bermuda') = NULL THEN 'NOT' ELSE 'OK' END) AS Bermuda,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'BT' AND name = 'Bhutan') = NULL THEN 'NOT' ELSE 'OK' END) AS Bhutan,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'BO' AND name = 'Bolivia') = NULL THEN 'NOT' ELSE 'OK' END) AS Bolivia,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'BQ' AND name = 'Bonaire, Sint Eustatius and Saba') = NULL THEN 'NOT' ELSE 'OK' END) AS Bonaire, Sint Eustatius and Saba,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'BA' AND name = 'Bosnia and Herzegovina') = NULL THEN 'NOT' ELSE 'OK' END) AS Bosnia and Herzegovina,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'BW' AND name = 'Botswana') = NULL THEN 'NOT' ELSE 'OK' END) AS Botswana,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'BR' AND name = 'Brazil') = NULL THEN 'NOT' ELSE 'OK' END) AS Brazil,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'BN' AND name = 'Brunei') = NULL THEN 'NOT' ELSE 'OK' END) AS Brunei,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'BG' AND name = 'Bulgaria') = NULL THEN 'NOT' ELSE 'OK' END) AS Bulgaria,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'BF' AND name = 'Burkina Faso') = NULL THEN 'NOT' ELSE 'OK' END) AS Burkina Faso,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'BI' AND name = 'Burundi') = NULL THEN 'NOT' ELSE 'OK' END) AS Burundi,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'KH' AND name = 'Cambodia') = NULL THEN 'NOT' ELSE 'OK' END) AS Cambodia,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'CM' AND name = 'Cameroon') = NULL THEN 'NOT' ELSE 'OK' END) AS Cameroon,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'CA' AND name = 'Canada') = NULL THEN 'NOT' ELSE 'OK' END) AS Canada,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'CV' AND name = 'Cape Verde') = NULL THEN 'NOT' ELSE 'OK' END) AS Cape Verde,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'CF' AND name = 'Central African') = NULL THEN 'NOT' ELSE 'OK' END) AS Central African,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'TD' AND name = 'Chad') = NULL THEN 'NOT' ELSE 'OK' END) AS Chad,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'CL' AND name = 'Chile') = NULL THEN 'NOT' ELSE 'OK' END) AS Chile,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'CN' AND name = 'China') = NULL THEN 'NOT' ELSE 'OK' END) AS China,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'CO' AND name = 'Colombia') = NULL THEN 'NOT' ELSE 'OK' END) AS Colombia,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'KM' AND name = 'Comoros') = NULL THEN 'NOT' ELSE 'OK' END) AS Comoros,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'CG' AND name = 'Congo') = NULL THEN 'NOT' ELSE 'OK' END) AS Congo,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'CR' AND name = 'Costa Rica') = NULL THEN 'NOT' ELSE 'OK' END) AS Costa Rica,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'CI' AND name = 'Cote D`Ivoire (Ivory Coast)') = NULL THEN 'NOT' ELSE 'OK' END) AS Cote D`Ivoire (Ivory Coast),
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'HR' AND name = 'Croatia') = NULL THEN 'NOT' ELSE 'OK' END) AS Croatia,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'CU' AND name = 'Cuba') = NULL THEN 'NOT' ELSE 'OK' END) AS Cuba,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'CY' AND name = 'Cyprus') = NULL THEN 'NOT' ELSE 'OK' END) AS Cyprus,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'CZ' AND name = 'Czech Republic') = NULL THEN 'NOT' ELSE 'OK' END) AS Czech Republic,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'CD' AND name = 'Democratic Republic') = NULL THEN 'NOT' ELSE 'OK' END) AS Democratic Republic,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'DK' AND name = 'Denmark') = NULL THEN 'NOT' ELSE 'OK' END) AS Denmark,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'DJ' AND name = 'Djibouti') = NULL THEN 'NOT' ELSE 'OK' END) AS Djibouti,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'DM' AND name = 'Dominica') = NULL THEN 'NOT' ELSE 'OK' END) AS Dominica,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'DO' AND name = 'Dominican Republic') = NULL THEN 'NOT' ELSE 'OK' END) AS Dominican Republic,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'TL' AND name = 'East Timor') = NULL THEN 'NOT' ELSE 'OK' END) AS East Timor,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'EC' AND name = 'Ecuador') = NULL THEN 'NOT' ELSE 'OK' END) AS Ecuador,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'EG' AND name = 'Egypt') = NULL THEN 'NOT' ELSE 'OK' END) AS Egypt,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'SV' AND name = 'El Salvador') = NULL THEN 'NOT' ELSE 'OK' END) AS El Salvador,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'GQ' AND name = 'Equatorial Guinea') = NULL THEN 'NOT' ELSE 'OK' END) AS Equatorial Guinea,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'ER' AND name = 'Eritrea') = NULL THEN 'NOT' ELSE 'OK' END) AS Eritrea,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'EE' AND name = 'Estonia') = NULL THEN 'NOT' ELSE 'OK' END) AS Estonia,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'ET' AND name = 'Ethiopia') = NULL THEN 'NOT' ELSE 'OK' END) AS Ethiopia,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'FJ' AND name = 'Fiji Islands') = NULL THEN 'NOT' ELSE 'OK' END) AS Fiji Islands,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'FI' AND name = 'Finland') = NULL THEN 'NOT' ELSE 'OK' END) AS Finland,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'FR' AND name = 'France') = NULL THEN 'NOT' ELSE 'OK' END) AS France,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'GA' AND name = 'Gabon') = NULL THEN 'NOT' ELSE 'OK' END) AS Gabon,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'GM' AND name = 'Gambia The') = NULL THEN 'NOT' ELSE 'OK' END) AS Gambia The,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'GE' AND name = 'Georgia') = NULL THEN 'NOT' ELSE 'OK' END) AS Georgia,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'DE' AND name = 'Germany') = NULL THEN 'NOT' ELSE 'OK' END) AS Germany,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'GH' AND name = 'Ghana') = NULL THEN 'NOT' ELSE 'OK' END) AS Ghana,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'GR' AND name = 'Greece') = NULL THEN 'NOT' ELSE 'OK' END) AS Greece,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'GD' AND name = 'Grenada') = NULL THEN 'NOT' ELSE 'OK' END) AS Grenada,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'GT' AND name = 'Guatemala') = NULL THEN 'NOT' ELSE 'OK' END) AS Guatemala,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'GN' AND name = 'Guinea') = NULL THEN 'NOT' ELSE 'OK' END) AS Guinea,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'GW' AND name = 'Guinea-Bissau') = NULL THEN 'NOT' ELSE 'OK' END) AS Guinea-Bissau,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'GY' AND name = 'Guyana') = NULL THEN 'NOT' ELSE 'OK' END) AS Guyana,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'HT' AND name = 'Haiti') = NULL THEN 'NOT' ELSE 'OK' END) AS Haiti,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'HN' AND name = 'Honduras') = NULL THEN 'NOT' ELSE 'OK' END) AS Honduras,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'HK' AND name = 'Hong Kong S.A.R.') = NULL THEN 'NOT' ELSE 'OK' END) AS Hong Kong S.A.R.,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'KH' AND name = 'Hong Kong S.A.R.') = NULL THEN 'NOT' ELSE 'OK' END) AS Hong Kong S.A.R.,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'HU' AND name = 'Hungary') = NULL THEN 'NOT' ELSE 'OK' END) AS Hungary,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'IS' AND name = 'Iceland') = NULL THEN 'NOT' ELSE 'OK' END) AS Iceland,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'IN' AND name = 'India') = NULL THEN 'NOT' ELSE 'OK' END) AS India,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'ID' AND name = 'Indonesia') = NULL THEN 'NOT' ELSE 'OK' END) AS Indonesia,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'IR' AND name = 'Iran') = NULL THEN 'NOT' ELSE 'OK' END) AS Iran,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'IQ' AND name = 'Iraq') = NULL THEN 'NOT' ELSE 'OK' END) AS Iraq,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'IE' AND name = 'Ireland') = NULL THEN 'NOT' ELSE 'OK' END) AS Ireland,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'IL' AND name = 'Israel') = NULL THEN 'NOT' ELSE 'OK' END) AS Israel,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'IT' AND name = 'Italy') = NULL THEN 'NOT' ELSE 'OK' END) AS Italy,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'JM' AND name = 'Jamaica') = NULL THEN 'NOT' ELSE 'OK' END) AS Jamaica,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'JP' AND name = 'Japan') = NULL THEN 'NOT' ELSE 'OK' END) AS Japan,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'JO' AND name = 'Jordan') = NULL THEN 'NOT' ELSE 'OK' END) AS Jordan,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'KZ' AND name = 'Kazakhstan') = NULL THEN 'NOT' ELSE 'OK' END) AS Kazakhstan,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'KE' AND name = 'Kenya') = NULL THEN 'NOT' ELSE 'OK' END) AS Kenya,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'KI' AND name = 'Kiribati') = NULL THEN 'NOT' ELSE 'OK' END) AS Kiribati,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'XK' AND name = 'Kosovo') = NULL THEN 'NOT' ELSE 'OK' END) AS Kosovo,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'KW' AND name = 'Kuwait') = NULL THEN 'NOT' ELSE 'OK' END) AS Kuwait,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'KG' AND name = 'Kyrgyzstan') = NULL THEN 'NOT' ELSE 'OK' END) AS Kyrgyzstan,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'LA' AND name = 'Laos') = NULL THEN 'NOT' ELSE 'OK' END) AS Laos,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'LV' AND name = 'Latvia') = NULL THEN 'NOT' ELSE 'OK' END) AS Latvia,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'LB' AND name = 'Lebanon') = NULL THEN 'NOT' ELSE 'OK' END) AS Lebanon,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'LS' AND name = 'Lesotho') = NULL THEN 'NOT' ELSE 'OK' END) AS Lesotho,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'LR' AND name = 'Liberia') = NULL THEN 'NOT' ELSE 'OK' END) AS Liberia,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'LY' AND name = 'Libya') = NULL THEN 'NOT' ELSE 'OK' END) AS Libya,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'LI' AND name = 'Liechtenstein') = NULL THEN 'NOT' ELSE 'OK' END) AS Liechtenstein,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'LT' AND name = 'Lithuania') = NULL THEN 'NOT' ELSE 'OK' END) AS Lithuania,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'LU' AND name = 'Luxembourg') = NULL THEN 'NOT' ELSE 'OK' END) AS Luxembourg,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'MK' AND name = 'Macedonia') = NULL THEN 'NOT' ELSE 'OK' END) AS Macedonia,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'MG' AND name = 'Madagascar') = NULL THEN 'NOT' ELSE 'OK' END) AS Madagascar,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'MW' AND name = 'Malawi') = NULL THEN 'NOT' ELSE 'OK' END) AS Malawi,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'MY' AND name = 'Malaysia') = NULL THEN 'NOT' ELSE 'OK' END) AS Malaysia,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'MV' AND name = 'Maldives') = NULL THEN 'NOT' ELSE 'OK' END) AS Maldives,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'ML' AND name = 'Mali') = NULL THEN 'NOT' ELSE 'OK' END) AS Mali,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'MT' AND name = 'Malta') = NULL THEN 'NOT' ELSE 'OK' END) AS Malta,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'MH' AND name = 'Marshall Islands') = NULL THEN 'NOT' ELSE 'OK' END) AS Marshall Islands,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'MR' AND name = 'Mauritania') = NULL THEN 'NOT' ELSE 'OK' END) AS Mauritania,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'MU' AND name = 'Mauritius') = NULL THEN 'NOT' ELSE 'OK' END) AS Mauritius,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'MX' AND name = 'Mexico') = NULL THEN 'NOT' ELSE 'OK' END) AS Mexico,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'FM' AND name = 'Micronesia') = NULL THEN 'NOT' ELSE 'OK' END) AS Micronesia,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'MD' AND name = 'Moldova') = NULL THEN 'NOT' ELSE 'OK' END) AS Moldova,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'MC' AND name = 'Monaco') = NULL THEN 'NOT' ELSE 'OK' END) AS Monaco,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'MN' AND name = 'Mongolia') = NULL THEN 'NOT' ELSE 'OK' END) AS Mongolia,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'ME' AND name = 'Montenegro') = NULL THEN 'NOT' ELSE 'OK' END) AS Montenegro,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'MA' AND name = 'Morocco') = NULL THEN 'NOT' ELSE 'OK' END) AS Morocco,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'MZ' AND name = 'Mozambique') = NULL THEN 'NOT' ELSE 'OK' END) AS Mozambique,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'MM' AND name = 'Myanmar') = NULL THEN 'NOT' ELSE 'OK' END) AS Myanmar,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'NA' AND name = 'Namibia') = NULL THEN 'NOT' ELSE 'OK' END) AS Namibia,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'NR' AND name = 'Nauru') = NULL THEN 'NOT' ELSE 'OK' END) AS Nauru,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'NP' AND name = 'Nepal') = NULL THEN 'NOT' ELSE 'OK' END) AS Nepal,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'NL' AND name = 'Netherlands') = NULL THEN 'NOT' ELSE 'OK' END) AS Netherlands,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'NZ' AND name = 'New Zealand') = NULL THEN 'NOT' ELSE 'OK' END) AS New Zealand,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'NI' AND name = 'Nicaragua') = NULL THEN 'NOT' ELSE 'OK' END) AS Nicaragua,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'NE' AND name = 'Niger') = NULL THEN 'NOT' ELSE 'OK' END) AS Niger,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'NG' AND name = 'Nigeria') = NULL THEN 'NOT' ELSE 'OK' END) AS Nigeria,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'KP' AND name = 'North Korea') = NULL THEN 'NOT' ELSE 'OK' END) AS North Korea,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'NO' AND name = 'Norway') = NULL THEN 'NOT' ELSE 'OK' END) AS Norway,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'OM' AND name = 'Oman') = NULL THEN 'NOT' ELSE 'OK' END) AS Oman,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'PK' AND name = 'Pakistan') = NULL THEN 'NOT' ELSE 'OK' END) AS Pakistan,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'PW' AND name = 'Palau') = NULL THEN 'NOT' ELSE 'OK' END) AS Palau,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'PA' AND name = 'Panama') = NULL THEN 'NOT' ELSE 'OK' END) AS Panama,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'PG' AND name = 'Papua new Guinea') = NULL THEN 'NOT' ELSE 'OK' END) AS Papua new Guinea,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'PY' AND name = 'Paraguay') = NULL THEN 'NOT' ELSE 'OK' END) AS Paraguay,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'PE' AND name = 'Peru') = NULL THEN 'NOT' ELSE 'OK' END) AS Peru,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'PH' AND name = 'Philippines') = NULL THEN 'NOT' ELSE 'OK' END) AS Philippines,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'PL' AND name = 'Poland') = NULL THEN 'NOT' ELSE 'OK' END) AS Poland,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'PT' AND name = 'Portugal') = NULL THEN 'NOT' ELSE 'OK' END) AS Portugal,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'PR' AND name = 'Puerto Rico') = NULL THEN 'NOT' ELSE 'OK' END) AS Puerto Rico,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'QA' AND name = 'Qatar') = NULL THEN 'NOT' ELSE 'OK' END) AS Qatar,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'RO' AND name = 'Romania') = NULL THEN 'NOT' ELSE 'OK' END) AS Romania,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'RU' AND name = 'Russia') = NULL THEN 'NOT' ELSE 'OK' END) AS Russia,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'RW' AND name = 'Rwanda') = NULL THEN 'NOT' ELSE 'OK' END) AS Rwanda,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'KN' AND name = 'Saint Kitts') = NULL THEN 'NOT' ELSE 'OK' END) AS Saint Kitts,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'LC' AND name = 'Saint Lucia') = NULL THEN 'NOT' ELSE 'OK' END) AS Saint Lucia,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'VC' AND name = 'Saint Vincent') = NULL THEN 'NOT' ELSE 'OK' END) AS Saint Vincent,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'WS' AND name = 'Samoa') = NULL THEN 'NOT' ELSE 'OK' END) AS Samoa,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'SM' AND name = 'San Marino') = NULL THEN 'NOT' ELSE 'OK' END) AS San Marino,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'ST' AND name = 'Sao Tome and Principe') = NULL THEN 'NOT' ELSE 'OK' END) AS Sao Tome and Principe,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'SA' AND name = 'Saudi Arabia') = NULL THEN 'NOT' ELSE 'OK' END) AS Saudi Arabia,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'SN' AND name = 'Senegal') = NULL THEN 'NOT' ELSE 'OK' END) AS Senegal,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'RS' AND name = 'Serbia') = NULL THEN 'NOT' ELSE 'OK' END) AS Serbia,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'SC' AND name = 'Seychelles') = NULL THEN 'NOT' ELSE 'OK' END) AS Seychelles,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'SL' AND name = 'Sierra Leone') = NULL THEN 'NOT' ELSE 'OK' END) AS Sierra Leone,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'SG' AND name = 'Singapore') = NULL THEN 'NOT' ELSE 'OK' END) AS Singapore,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'SK' AND name = 'Slovakia') = NULL THEN 'NOT' ELSE 'OK' END) AS Slovakia,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'SI' AND name = 'Slovenia') = NULL THEN 'NOT' ELSE 'OK' END) AS Slovenia,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'SB' AND name = 'Solomon Islands') = NULL THEN 'NOT' ELSE 'OK' END) AS Solomon Islands,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'SO' AND name = 'Somalia') = NULL THEN 'NOT' ELSE 'OK' END) AS Somalia,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'ZA' AND name = 'South Africa') = NULL THEN 'NOT' ELSE 'OK' END) AS South Africa,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'KR' AND name = 'South Korea') = NULL THEN 'NOT' ELSE 'OK' END) AS South Korea,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'SS' AND name = 'South Sudan') = NULL THEN 'NOT' ELSE 'OK' END) AS South Sudan,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'ES' AND name = 'Spain') = NULL THEN 'NOT' ELSE 'OK' END) AS Spain,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'LK' AND name = 'Sri Lanka') = NULL THEN 'NOT' ELSE 'OK' END) AS Sri Lanka,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'SD' AND name = 'Sudan') = NULL THEN 'NOT' ELSE 'OK' END) AS Sudan,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'SR' AND name = 'Suriname') = NULL THEN 'NOT' ELSE 'OK' END) AS Suriname,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'SZ' AND name = 'Swaziland') = NULL THEN 'NOT' ELSE 'OK' END) AS Swaziland,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'SE' AND name = 'Sweden') = NULL THEN 'NOT' ELSE 'OK' END) AS Sweden,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'CH' AND name = 'Switzerland') = NULL THEN 'NOT' ELSE 'OK' END) AS Switzerland,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'SY' AND name = 'Syria') = NULL THEN 'NOT' ELSE 'OK' END) AS Syria,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'TW' AND name = 'Taiwan') = NULL THEN 'NOT' ELSE 'OK' END) AS Taiwan,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'TJ' AND name = 'Tajikistan') = NULL THEN 'NOT' ELSE 'OK' END) AS Tajikistan,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'TZ' AND name = 'Tanzania') = NULL THEN 'NOT' ELSE 'OK' END) AS Tanzania,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'TH' AND name = 'Thailand') = NULL THEN 'NOT' ELSE 'OK' END) AS Thailand,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'BS' AND name = 'The Bahamas') = NULL THEN 'NOT' ELSE 'OK' END) AS The Bahamas,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'TG' AND name = 'Togo') = NULL THEN 'NOT' ELSE 'OK' END) AS Togo,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'TO' AND name = 'Tonga') = NULL THEN 'NOT' ELSE 'OK' END) AS Tonga,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'TT' AND name = 'Trinidad And Tobago') = NULL THEN 'NOT' ELSE 'OK' END) AS Trinidad And Tobago,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'TN' AND name = 'Tunisia') = NULL THEN 'NOT' ELSE 'OK' END) AS Tunisia,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'TR' AND name = 'Turkey') = NULL THEN 'NOT' ELSE 'OK' END) AS Turkey,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'TM' AND name = 'Turkmenistan') = NULL THEN 'NOT' ELSE 'OK' END) AS Turkmenistan,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'TV' AND name = 'Tuvalu') = NULL THEN 'NOT' ELSE 'OK' END) AS Tuvalu,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'UG' AND name = 'Uganda') = NULL THEN 'NOT' ELSE 'OK' END) AS Uganda,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'UA' AND name = 'Ukraine') = NULL THEN 'NOT' ELSE 'OK' END) AS Ukraine,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'AE' AND name = 'United Arab Emirates') = NULL THEN 'NOT' ELSE 'OK' END) AS United Arab Emirates,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'GB' AND name = 'United Kingdom' AS 'United Kingdom)
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'US' AND name = 'United States' AS 'United States)
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'UY' AND name = 'Uruguay') = NULL THEN 'NOT' ELSE 'OK' END) AS Uruguay,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'UZ' AND name = 'Uzbekistan') = NULL THEN 'NOT' ELSE 'OK' END) AS Uzbekistan,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'VU' AND name = 'Vanuatu') = NULL THEN 'NOT' ELSE 'OK' END) AS Vanuatu,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'VE' AND name = 'Venezuela') = NULL THEN 'NOT' ELSE 'OK' END) AS Venezuela,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'VI' AND name = 'Virgin Islands') = NULL THEN 'NOT' ELSE 'OK' END) AS Virgin Islands,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'YE' AND name = 'Yemen') = NULL THEN 'NOT' ELSE 'OK' END) AS Yemen,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'ZM' AND name = 'Zambia') = NULL THEN 'NOT' ELSE 'OK' END) AS Zambia,
  (CASE WHEN (SELECT id FROM countries WHERE iso2 = 'ZW' AND name = 'Zimbabwe') = NULL THEN 'NOT' ELSE 'OK' END) AS Zimbabwe';