/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: O4X2MKhZxKYekfAvn2FgmrGU3gK3sceS6N1lWOMO94YRDVhLRC0Jona87/3rd6Y+8IgrKjYCy2MoaC6tf58sEg==
 */

/* eslint-disable */
// tslint:disable

type PaymentType = 'acquisition' | 'monthly_payment';
export type {PaymentType}
