/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: R6DS+LPiDaUutUUvsqbW8OE039/dVcjFjhdjn6ofolkHrpQQ0NHry/b3IFUhN5R17c8cWze+RPG09FjvuuqFDA==
 */

/* eslint-disable */
// tslint:disable

import Bots from './bots'
import PhoneNumbers from './phone_numbers'

interface BotsPhoneNumbers {
  bot_id: Bots['id']
  phone_number_id: PhoneNumbers['id']
}
export default BotsPhoneNumbers;

interface BotsPhoneNumbers_InsertParameters {
  bot_id: Bots['id']
  phone_number_id: PhoneNumbers['id']
}
export type {BotsPhoneNumbers_InsertParameters}
