/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: J64nyqQALlIUE8PSiA5rntCkAoRV40dTzRcSuKa9l7qIzyUvCXDc1erkg1tdVpmq3zE4iXj4WKAmIX5JmcVCcQ==
 */

/* eslint-disable */
// tslint:disable

interface Bots {
  bot_name: string
  /**
   * @default '2022-06-27'::date
   */
  created_at: Date
  /**
   * @default nextval('bots_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'bots_id'}
  is_active: (boolean) | null
  steps: (any) | null
  /**
   * @default '2022-06-27'::date
   */
  updated_at: Date
}
export default Bots;

interface Bots_InsertParameters {
  bot_name: string
  /**
   * @default '2022-06-27'::date
   */
  created_at?: Date
  /**
   * @default nextval('bots_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'bots_id'}
  is_active?: (boolean) | null
  steps?: (any) | null
  /**
   * @default '2022-06-27'::date
   */
  updated_at?: Date
}
export type {Bots_InsertParameters}
