/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: joz+aAxT/P9YQbkwCr2YZU8LDPFilVnajF+y+ZAfYwVqaz2eFN8AxPee+9lbYcXV5RcIikyDWB9ZwMLXx0nBfw==
 */

/* eslint-disable */
// tslint:disable

import Users from './users'

interface Bots {
  bot_name: string
  /**
   * @default '2022-09-27'::date
   */
  created_at: Date
  /**
   * @default nextval('bots_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'bots_id'}
  /**
   * @default true
   */
  is_active: (boolean) | null
  steps: (any) | null
  /**
   * @default '2022-09-27'::date
   */
  updated_at: Date
  user_id: Users['id']
}
export default Bots;

interface Bots_InsertParameters {
  bot_name: string
  /**
   * @default '2022-09-27'::date
   */
  created_at?: Date
  /**
   * @default nextval('bots_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'bots_id'}
  /**
   * @default true
   */
  is_active?: (boolean) | null
  steps?: (any) | null
  /**
   * @default '2022-09-27'::date
   */
  updated_at?: Date
  user_id: Users['id']
}
export type {Bots_InsertParameters}
