/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: gvNzp00aK9MavzHE+d+B07F3BRVBUggq6OMZ/+2GedBKVT/CD/OfKh8StHcfYrF/XCgGGLY9mDPeHSDQ4QbugA==
 */

import { Step } from '../../../../Domain/Entities/Steps/Step'

/* eslint-disable */
// tslint:disable

interface Bots {
  bot_name: string
  /**
   * @default '2022-06-24'::date
   */
  created_at: Date
  /**
   * @default nextval('bots_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'bots_id'}
  is_active: (boolean) | null
  steps: Step[] | null
  /**
   * @default '2022-06-24'::date
   */
  updated_at: Date
}
export default Bots;

interface Bots_InsertParameters {
  bot_name: string
  /**
   * @default '2022-06-24'::date
   */
  created_at?: Date
  /**
   * @default nextval('bots_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'bots_id'}
  is_active?: (boolean) | null
  steps?: (any) | null
  /**
   * @default '2022-06-24'::date
   */
  updated_at?: Date
}
export type {Bots_InsertParameters}
