/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: GNSPTb/6ojioerlu+/P1LVi42RYoEG1vboM/x/NyJYGMcUMx6rc0CBAWTmKyYdOWVSaYdPLN4gbaH7KzHA2SnQ==
 */

/* eslint-disable */
// tslint:disable

interface Cities {
  /**
   * @default nextval('cities_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'cities_id'}
  name: string
}
export default Cities;

interface Cities_InsertParameters {
  /**
   * @default nextval('cities_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'cities_id'}
  name: string
}
export type {Cities_InsertParameters}
