/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: x/Fx9jT12Z5GiUpq4MjfQYcriUnn0GNd9mE3RBfPp/e23Uxr+6Ay5lOPgBjkhxCwS8+JKyEwUrZ8LU6jguq/0w==
 */

/* eslint-disable */
// tslint:disable

import States from './states'

interface Cities {
  /**
   * @default '2022-07-19'::date
   */
  created_at: Date
  /**
   * @default nextval('cities_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'cities_id'}
  /**
   * @default true
   */
  is_active: (boolean) | null
  name: string
  state_id: States['id']
  /**
   * @default '2022-07-19'::date
   */
  updated_at: Date
}
export default Cities;

interface Cities_InsertParameters {
  /**
   * @default '2022-07-19'::date
   */
  created_at?: Date
  /**
   * @default nextval('cities_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'cities_id'}
  /**
   * @default true
   */
  is_active?: (boolean) | null
  name: string
  state_id: States['id']
  /**
   * @default '2022-07-19'::date
   */
  updated_at?: Date
}
export type {Cities_InsertParameters}
