/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: jzf3tLRvoVK2+McvOP5JPWitEtv6BFC3FXjczlBWEpY/NKHjOPbs6QjOkw7dPvbUTUj96tHZ5ZUSRi7rkst2kg==
 */

/* eslint-disable */
// tslint:disable

import States from './states'

interface Cities {
  /**
   * @default nextval('cities_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'cities_id'}
  name: string
  state_id: States['id']
}
export default Cities;

interface Cities_InsertParameters {
  /**
   * @default nextval('cities_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'cities_id'}
  name: string
  state_id: States['id']
}
export type {Cities_InsertParameters}
