/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: cvC6W7vRylp9usvksPHY7amGDnUGMEW74JM45E43Ib5YChkOX2nrP+OWAo+DW8D/AvqdGWzCPto4+GL5rIhRIQ==
 */

/* eslint-disable */
// tslint:disable

interface Countries {
  /**
   * @default '2022-07-19'::date
   */
  created_at: Date
  currency: (string) | null
  emoji: (string) | null
  /**
   * @default nextval('countries_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'countries_id'}
  /**
   * @default true
   */
  is_active: (boolean) | null
  iso2: string
  iso3: string
  name: string
  phone_code: (string) | null
  /**
   * @default '2022-07-19'::date
   */
  updated_at: Date
}
export default Countries;

interface Countries_InsertParameters {
  /**
   * @default '2022-07-19'::date
   */
  created_at?: Date
  currency?: (string) | null
  emoji?: (string) | null
  /**
   * @default nextval('countries_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'countries_id'}
  /**
   * @default true
   */
  is_active?: (boolean) | null
  iso2: string
  iso3: string
  name: string
  phone_code?: (string) | null
  /**
   * @default '2022-07-19'::date
   */
  updated_at?: Date
}
export type {Countries_InsertParameters}
