/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 65ZDCBROMfwMKYYJ0uYEIiOrBU9OOy/8Tosl3xL51gU3gXmt90XrOxh8SHb+carS/G1GBN0xggr24zx4fHX+Kw==
 */

/* eslint-disable */
// tslint:disable

interface Countries {
  currency: (string) | null
  emoji: (string) | null
  /**
   * @default nextval('countries_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'countries_id'}
  iso2: string
  iso3: string
  name: string
  phone_code: (string) | null
}
export default Countries;

interface Countries_InsertParameters {
  currency?: (string) | null
  emoji?: (string) | null
  /**
   * @default nextval('countries_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'countries_id'}
  iso2: string
  iso3: string
  name: string
  phone_code?: (string) | null
}
export type {Countries_InsertParameters}
