/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: yEUnitJReMVP8NHvMbcVz5ul+gNc/UwMUnsHCahXWq0TxL/yyUM1bRJywoivHATKWTHWWyAWQG6JQ5N/r9T1Hg==
 */

/* eslint-disable */
// tslint:disable

import CustomPlans from './custom_plans'
import Features from './features'

interface CustomPlanFeatures {
  /**
   * @default '2022-06-27'::date
   */
  created_at: Date
  custom_plan_id: (CustomPlans['id']) | null
  feature_id: (Features['id']) | null
  is_active: (boolean) | null
  max_limit: (number) | null
  /**
   * @default '2022-06-27'::date
   */
  updated_at: Date
}
export default CustomPlanFeatures;

interface CustomPlanFeatures_InsertParameters {
  /**
   * @default '2022-06-27'::date
   */
  created_at?: Date
  custom_plan_id?: (CustomPlans['id']) | null
  feature_id?: (Features['id']) | null
  is_active?: (boolean) | null
  max_limit?: (number) | null
  /**
   * @default '2022-06-27'::date
   */
  updated_at?: Date
}
export type {CustomPlanFeatures_InsertParameters}
