/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: P37Kmzeilbb1axU3wlA7Ko0Yap7UDNdukGwdNWnQ35EiHewMiTionb3NqzXsDlqv7CnTptJ2Now9EXureObbpw==
 */

/* eslint-disable */
// tslint:disable

import DefaultPlans from './default_plans'
import Features from './features'

interface DefaultPlanFeatures {
  default_plan_id: (DefaultPlans['id']) | null
  feature_id: (Features['id']) | null
  is_active: (boolean) | null
  max_limit: (number) | null
}
export default DefaultPlanFeatures;

interface DefaultPlanFeatures_InsertParameters {
  default_plan_id?: (DefaultPlans['id']) | null
  feature_id?: (Features['id']) | null
  is_active?: (boolean) | null
  max_limit?: (number) | null
}
export type {DefaultPlanFeatures_InsertParameters}
