/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: Ok9GYueQs4omb6LnKI/UW4VzWxP8joWMLNI/g2FoplanqQCMrxZBQE/yVoool1jIzghEHkSnsSfg8czNero2Sw==
 */

/* eslint-disable */
// tslint:disable

interface DefaultPlans {
  /**
   * @default nextval('default_plans_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'default_plans_id'}
  name: string
  price: string
}
export default DefaultPlans;

interface DefaultPlans_InsertParameters {
  /**
   * @default nextval('default_plans_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'default_plans_id'}
  name: string
  price: string
}
export type {DefaultPlans_InsertParameters}
