/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: SbL+Xp6sDakxAq4SDiP5LzABw3hsC5Xt8cJOaHoFoEVaf6+S/mO8nWcE6FZ+04hpm0srJsniXSM2ZyxgiXYjYw==
 */

/* eslint-disable */
// tslint:disable

interface FeatureTypes {
  /**
   * @default nextval('feature_types_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'feature_types_id'}
  name: string
}
export default FeatureTypes;

interface FeatureTypes_InsertParameters {
  /**
   * @default nextval('feature_types_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'feature_types_id'}
  name: string
}
export type {FeatureTypes_InsertParameters}
