/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 5TbQbTyvO81fuinHVC1jcYFr/7TTtOdkLiWLm0TgO9TOAnmQUeEGwMw0dvdV9wpjQvocXgl2Cfpg6d3CVcmVdg==
 */

/* eslint-disable */
// tslint:disable

import FeatureTypes from './feature_types'

interface Features {
  /**
   * @default '2022-07-01'::date
   */
  created_at: Date
  /**
   * @default nextval('features_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'features_id'}
  is_active: (boolean) | null
  name: string
  type_id: (FeatureTypes['id']) | null
  /**
   * @default '2022-07-01'::date
   */
  updated_at: Date
}
export default Features;

interface Features_InsertParameters {
  /**
   * @default '2022-07-01'::date
   */
  created_at?: Date
  /**
   * @default nextval('features_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'features_id'}
  is_active?: (boolean) | null
  name: string
  type_id?: (FeatureTypes['id']) | null
  /**
   * @default '2022-07-01'::date
   */
  updated_at?: Date
}
export type {Features_InsertParameters}
