/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 0/VwumkZAY4Xxk9yD2S75GOPstxNxuCEnIWe6Wajk5qGd/GZFgB+j/9NxOrxDnRqf8/Vnf8IRs00/NnrTQ6c4Q==
 */

/* eslint-disable */
// tslint:disable

import Bots, {Bots_InsertParameters} from './bots'
import Cities, {Cities_InsertParameters} from './cities'
import Countries, {Countries_InsertParameters} from './countries'
import CustomPlanFeatures, {CustomPlanFeatures_InsertParameters} from './custom_plan_features'
import CustomPlans, {CustomPlans_InsertParameters} from './custom_plans'
import DefaultPlanFeatures, {DefaultPlanFeatures_InsertParameters} from './default_plan_features'
import DefaultPlans, {DefaultPlans_InsertParameters} from './default_plans'
import FeatureTypes, {FeatureTypes_InsertParameters} from './feature_types'
import Features, {Features_InsertParameters} from './features'
import Payments, {Payments_InsertParameters} from './payments'
import Pgmigrations, {Pgmigrations_InsertParameters} from './pgmigrations'
import States, {States_InsertParameters} from './states'
import UserPlan, {UserPlan_InsertParameters} from './user_plan'
import Users, {Users_InsertParameters} from './users'
import UsersBots, {UsersBots_InsertParameters} from './users_bots'

interface DatabaseSchema {
  bots: {record: Bots, insert: Bots_InsertParameters};
  cities: {record: Cities, insert: Cities_InsertParameters};
  countries: {record: Countries, insert: Countries_InsertParameters};
  custom_plan_features: {record: CustomPlanFeatures, insert: CustomPlanFeatures_InsertParameters};
  custom_plans: {record: CustomPlans, insert: CustomPlans_InsertParameters};
  default_plan_features: {record: DefaultPlanFeatures, insert: DefaultPlanFeatures_InsertParameters};
  default_plans: {record: DefaultPlans, insert: DefaultPlans_InsertParameters};
  feature_types: {record: FeatureTypes, insert: FeatureTypes_InsertParameters};
  features: {record: Features, insert: Features_InsertParameters};
  payments: {record: Payments, insert: Payments_InsertParameters};
  pgmigrations: {record: Pgmigrations, insert: Pgmigrations_InsertParameters};
  states: {record: States, insert: States_InsertParameters};
  user_plan: {record: UserPlan, insert: UserPlan_InsertParameters};
  users: {record: Users, insert: Users_InsertParameters};
  users_bots: {record: UsersBots, insert: UsersBots_InsertParameters};
}
export default DatabaseSchema;

/**
 * JSON serialize values (v) if the table name (t) and column name (c)
 * is a JSON or JSONB column.
 * This is necessary if you want to store values that are not plain objects
 * in a JSON or JSONB column.
 */
function serializeValue(t: string, c: string, v: unknown): unknown {
  if (t === "bots" && c === "steps") {
    return JSON.stringify(v);
  }
  return v;
}
export {serializeValue}

export type {
  Bots,
  Bots_InsertParameters,
  Cities,
  Cities_InsertParameters,
  Countries,
  Countries_InsertParameters,
  CustomPlans,
  CustomPlans_InsertParameters,
  FeatureTypes,
  FeatureTypes_InsertParameters,
  Features,
  Features_InsertParameters,
  CustomPlanFeatures,
  CustomPlanFeatures_InsertParameters,
  DefaultPlans,
  DefaultPlans_InsertParameters,
  DefaultPlanFeatures,
  DefaultPlanFeatures_InsertParameters,
  States,
  States_InsertParameters,
  Users,
  Users_InsertParameters,
  UserPlan,
  UserPlan_InsertParameters,
  Payments,
  Payments_InsertParameters,
  Pgmigrations,
  Pgmigrations_InsertParameters,
  UsersBots,
  UsersBots_InsertParameters,
}
