/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: gG7O8eHBh7XjFD9BXcQIs3vVNTUxIK33usW3ssrc5GTPQA2KJOgpGe7XM6nldOJNXsWFjpQC9ZMuorC6hYHoqA==
 */

/* eslint-disable */
// tslint:disable

import Bots, {Bots_InsertParameters} from './bots'
import BotsPhoneNumbers, {BotsPhoneNumbers_InsertParameters} from './bots_phone_numbers'
import Cities, {Cities_InsertParameters} from './cities'
import Countries, {Countries_InsertParameters} from './countries'
import Features, {Features_InsertParameters} from './features'
import Payments, {Payments_InsertParameters} from './payments'
import Pgmigrations, {Pgmigrations_InsertParameters} from './pgmigrations'
import PhoneNumbers, {PhoneNumbers_InsertParameters} from './phone_numbers'
import Plans, {Plans_InsertParameters} from './plans'
import PlansFeatures, {PlansFeatures_InsertParameters} from './plans_features'
import States, {States_InsertParameters} from './states'
import Users, {Users_InsertParameters} from './users'

interface DatabaseSchema {
  bots: {record: Bots, insert: Bots_InsertParameters};
  bots_phone_numbers: {record: BotsPhoneNumbers, insert: BotsPhoneNumbers_InsertParameters};
  cities: {record: Cities, insert: Cities_InsertParameters};
  countries: {record: Countries, insert: Countries_InsertParameters};
  features: {record: Features, insert: Features_InsertParameters};
  payments: {record: Payments, insert: Payments_InsertParameters};
  pgmigrations: {record: Pgmigrations, insert: Pgmigrations_InsertParameters};
  phone_numbers: {record: PhoneNumbers, insert: PhoneNumbers_InsertParameters};
  plans: {record: Plans, insert: Plans_InsertParameters};
  plans_features: {record: PlansFeatures, insert: PlansFeatures_InsertParameters};
  states: {record: States, insert: States_InsertParameters};
  users: {record: Users, insert: Users_InsertParameters};
}
export default DatabaseSchema;

/**
 * JSON serialize values (v) if the table name (t) and column name (c)
 * is a JSON or JSONB column.
 * This is necessary if you want to store values that are not plain objects
 * in a JSON or JSONB column.
 */
function serializeValue(t: string, c: string, v: unknown): unknown {
  if (t === "bots" && c === "steps") {
    return JSON.stringify(v);
  }
  return v;
}
export {serializeValue}

export type {
  Countries,
  Countries_InsertParameters,
  States,
  States_InsertParameters,
  Cities,
  Cities_InsertParameters,
  PhoneNumbers,
  PhoneNumbers_InsertParameters,
  Plans,
  Plans_InsertParameters,
  Users,
  Users_InsertParameters,
  Bots,
  Bots_InsertParameters,
  BotsPhoneNumbers,
  BotsPhoneNumbers_InsertParameters,
  Features,
  Features_InsertParameters,
  Payments,
  Payments_InsertParameters,
  Pgmigrations,
  Pgmigrations_InsertParameters,
  PlansFeatures,
  PlansFeatures_InsertParameters,
}
