/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: jqwlWAxKjsi/QjxwmOIyMl4E/deyCYEazLH6ixySNzovP7l7M5vE0Vx2yEWWCDx5kd5vUcCDYFOYMNsLz04flw==
 */

/* eslint-disable */
// tslint:disable

import Bots, {Bots_InsertParameters} from './bots'
import Cities, {Cities_InsertParameters} from './cities'
import Countries, {Countries_InsertParameters} from './countries'
import CustomPlanFeature, {CustomPlanFeature_InsertParameters} from './custom_plan_feature'
import CustomPlans, {CustomPlans_InsertParameters} from './custom_plans'
import DefaultPlanFeature, {DefaultPlanFeature_InsertParameters} from './default_plan_feature'
import DefaultPlans, {DefaultPlans_InsertParameters} from './default_plans'
import Features, {Features_InsertParameters} from './features'
import Payments, {Payments_InsertParameters} from './payments'
import Pgmigrations, {Pgmigrations_InsertParameters} from './pgmigrations'
import PlanFeatureType, {PlanFeatureType_InsertParameters} from './plan_feature_type'
import States, {States_InsertParameters} from './states'
import UserPlan, {UserPlan_InsertParameters} from './user_plan'
import Users, {Users_InsertParameters} from './users'
import UsersBots, {UsersBots_InsertParameters} from './users_bots'

interface DatabaseSchema {
  bots: {record: Bots, insert: Bots_InsertParameters};
  cities: {record: Cities, insert: Cities_InsertParameters};
  countries: {record: Countries, insert: Countries_InsertParameters};
  custom_plan_feature: {record: CustomPlanFeature, insert: CustomPlanFeature_InsertParameters};
  custom_plans: {record: CustomPlans, insert: CustomPlans_InsertParameters};
  default_plan_feature: {record: DefaultPlanFeature, insert: DefaultPlanFeature_InsertParameters};
  default_plans: {record: DefaultPlans, insert: DefaultPlans_InsertParameters};
  features: {record: Features, insert: Features_InsertParameters};
  payments: {record: Payments, insert: Payments_InsertParameters};
  pgmigrations: {record: Pgmigrations, insert: Pgmigrations_InsertParameters};
  plan_feature_type: {record: PlanFeatureType, insert: PlanFeatureType_InsertParameters};
  states: {record: States, insert: States_InsertParameters};
  user_plan: {record: UserPlan, insert: UserPlan_InsertParameters};
  users: {record: Users, insert: Users_InsertParameters};
  users_bots: {record: UsersBots, insert: UsersBots_InsertParameters};
}
export default DatabaseSchema;

/**
 * JSON serialize values (v) if the table name (t) and column name (c)
 * is a JSON or JSONB column.
 * This is necessary if you want to store values that are not plain objects
 * in a JSON or JSONB column.
 */
function serializeValue(t: string, c: string, v: unknown): unknown {
  if (t === "bots" && c === "steps") {
    return JSON.stringify(v);
  }
  return v;
}
export {serializeValue}

export type {
  Bots,
  Bots_InsertParameters,
  Cities,
  Cities_InsertParameters,
  Countries,
  Countries_InsertParameters,
  CustomPlans,
  CustomPlans_InsertParameters,
  Features,
  Features_InsertParameters,
  PlanFeatureType,
  PlanFeatureType_InsertParameters,
  CustomPlanFeature,
  CustomPlanFeature_InsertParameters,
  DefaultPlans,
  DefaultPlans_InsertParameters,
  DefaultPlanFeature,
  DefaultPlanFeature_InsertParameters,
  States,
  States_InsertParameters,
  Users,
  Users_InsertParameters,
  UserPlan,
  UserPlan_InsertParameters,
  Payments,
  Payments_InsertParameters,
  Pgmigrations,
  Pgmigrations_InsertParameters,
  UsersBots,
  UsersBots_InsertParameters,
}
