/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 1qxc51aVMt5mrc85MFpDB9ThK9zUN4BLLGlRiV5BbX9irEeI2CvS1s08VK1pNUhWMn27+d0kb/Ayw7aUmxbZng==
 */

/* eslint-disable */
// tslint:disable

import Plans from './plans'
import Users from './users'

interface Payments {
  /**
   * @default '2022-07-12'::date
   */
  created_at: Date
  /**
   * @default nextval('payments_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'payments_id'}
  payment_date: (Date) | null
  plan_id: (Plans['id']) | null
  reference_month: number
  reference_year: number
  send_date: (Date) | null
  /**
   * @default '2022-07-12'::date
   */
  updated_at: Date
  user_id: (Users['id']) | null
  was_paid: (boolean) | null
  was_sent: (boolean) | null
}
export default Payments;

interface Payments_InsertParameters {
  /**
   * @default '2022-07-12'::date
   */
  created_at?: Date
  /**
   * @default nextval('payments_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'payments_id'}
  payment_date?: (Date) | null
  plan_id?: (Plans['id']) | null
  reference_month: number
  reference_year: number
  send_date?: (Date) | null
  /**
   * @default '2022-07-12'::date
   */
  updated_at?: Date
  user_id?: (Users['id']) | null
  was_paid?: (boolean) | null
  was_sent?: (boolean) | null
}
export type {Payments_InsertParameters}
