/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: fNyudkTJVsz9Pkt3DJBwaqt/DAmPli6enIhBWebX4FaVX+mkTTWHBZeilmup7JZACQ57zzbUEVtfLd9E8lvS5Q==
 */

/* eslint-disable */
// tslint:disable

interface PhoneNumbers {
  /**
   * @default '2022-07-19'::date
   */
  created_at: Date
  /**
   * @default nextval('phone_numbers_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'phone_numbers_id'}
  /**
   * @default true
   */
  is_active: (boolean) | null
  /**
   * @default '2022-07-19'::date
   */
  updated_at: Date
  whatsapp_id: (string) | null
  whatsapp_number: string
}
export default PhoneNumbers;

interface PhoneNumbers_InsertParameters {
  /**
   * @default '2022-07-19'::date
   */
  created_at?: Date
  /**
   * @default nextval('phone_numbers_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'phone_numbers_id'}
  /**
   * @default true
   */
  is_active?: (boolean) | null
  /**
   * @default '2022-07-19'::date
   */
  updated_at?: Date
  whatsapp_id?: (string) | null
  whatsapp_number: string
}
export type {PhoneNumbers_InsertParameters}
