/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: MQtmDURhIPCmBmmjR3keS8kKK6lGpGnRaayc+qojJajaeROF6VZvwe3XUQX2jDoayjWpcUvJjEg0OmRT5kBICw==
 */

/* eslint-disable */
// tslint:disable

interface PhoneNumbers {
  /**
   * @default '2022-07-12'::date
   */
  created_at: Date
  /**
   * @default nextval('phone_numbers_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'phone_numbers_id'}
  /**
   * @default false
   */
  is_active: (boolean) | null
  /**
   * @default '2022-07-12'::date
   */
  updated_at: Date
  whatsapp_id: string
  whatsapp_number: string
}
export default PhoneNumbers;

interface PhoneNumbers_InsertParameters {
  /**
   * @default '2022-07-12'::date
   */
  created_at?: Date
  /**
   * @default nextval('phone_numbers_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'phone_numbers_id'}
  /**
   * @default false
   */
  is_active?: (boolean) | null
  /**
   * @default '2022-07-12'::date
   */
  updated_at?: Date
  whatsapp_id: string
  whatsapp_number: string
}
export type {PhoneNumbers_InsertParameters}
