/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: T/Hmljec+a0HJXCNjXAMtsqGRCaKSsWC7ohE2Q786Q2a8tUxnYSUOzhSlI3xkAIGyWFUqsCrpjDHTUKH2zUrBw==
 */

/* eslint-disable */
// tslint:disable

import Features from './features'
import Plans from './plans'

interface PlansFeatures {
  /**
   * @default '2022-07-01'::date
   */
  created_at: Date
  feature_id: (Features['id']) | null
  is_active: (boolean) | null
  max_limit: (number) | null
  plan_id: (Plans['id']) | null
  /**
   * @default '2022-07-01'::date
   */
  updated_at: Date
}
export default PlansFeatures;

interface PlansFeatures_InsertParameters {
  /**
   * @default '2022-07-01'::date
   */
  created_at?: Date
  feature_id?: (Features['id']) | null
  is_active?: (boolean) | null
  max_limit?: (number) | null
  plan_id?: (Plans['id']) | null
  /**
   * @default '2022-07-01'::date
   */
  updated_at?: Date
}
export type {PlansFeatures_InsertParameters}
