/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: PxGpJ1r13KkWB7BbIPIxokfB5XGirjWxzd8yu17Zx0YAExLUyv7U8uIwzCHSwfNzBVZ4gZHLmFOV05C/3itwzg==
 */

/* eslint-disable */
// tslint:disable

interface Plans {
  /**
   * @default '2022-07-01'::date
   */
  created_at: Date
  /**
   * @default nextval('plans_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'plans_id'}
  /**
   * @default true
   */
  is_active: (boolean) | null
  is_custom_plan: boolean
  name: (string) | null
  price: string
  /**
   * @default '2022-07-01'::date
   */
  updated_at: Date
}
export default Plans;

interface Plans_InsertParameters {
  /**
   * @default '2022-07-01'::date
   */
  created_at?: Date
  /**
   * @default nextval('plans_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'plans_id'}
  /**
   * @default true
   */
  is_active?: (boolean) | null
  is_custom_plan: boolean
  name?: (string) | null
  price: string
  /**
   * @default '2022-07-01'::date
   */
  updated_at?: Date
}
export type {Plans_InsertParameters}
