/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 525ZlgdczafoHAwakYMAIVQBGZcI5rl1q/lW3U/6NbCfCagVsOXymE7lskb5boWTjllIF8tFaS124kWBH4BRXw==
 */

/* eslint-disable */
// tslint:disable

interface PlanFeatureType {
  /**
   * @default nextval('plan_feature_type_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'plan_feature_type_id'}
  name: string
}
export default PlanFeatureType;

interface PlanFeatureType_InsertParameters {
  /**
   * @default nextval('plan_feature_type_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'plan_feature_type_id'}
  name: string
}
export type {PlanFeatureType_InsertParameters}
