/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: dngxjprkN2HtS9fjIQ2eYWly2u6QB9O7WDPh0P8YkLsEJ+pFPTMPs5W4A+mnMIkQy8xEWRq3922mSjeaYjuRdw==
 */

/* eslint-disable */
// tslint:disable

import Countries from './countries'

interface States {
  country_id: Countries['id']
  /**
   * @default nextval('states_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'states_id'}
  iso2: string
  name: string
  state_code: string
}
export default States;

interface States_InsertParameters {
  country_id: Countries['id']
  /**
   * @default nextval('states_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'states_id'}
  iso2: string
  name: string
  state_code: string
}
export type {States_InsertParameters}
