/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: CseWmxlOuowWe5aGyr/qyjduODYKcfknj0OP5GR2R67VD2yrQFubDwtuCBIOOPKdA+bLDEIhyn4/SSBwuvWVww==
 */

/* eslint-disable */
// tslint:disable

import Countries from './countries'

interface States {
  country_id: Countries['id']
  /**
   * @default '2022-07-19'::date
   */
  created_at: Date
  /**
   * @default nextval('states_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'states_id'}
  /**
   * @default true
   */
  is_active: (boolean) | null
  name: string
  state_code: string
  /**
   * @default '2022-07-19'::date
   */
  updated_at: Date
}
export default States;

interface States_InsertParameters {
  country_id: Countries['id']
  /**
   * @default '2022-07-19'::date
   */
  created_at?: Date
  /**
   * @default nextval('states_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'states_id'}
  /**
   * @default true
   */
  is_active?: (boolean) | null
  name: string
  state_code: string
  /**
   * @default '2022-07-19'::date
   */
  updated_at?: Date
}
export type {States_InsertParameters}
