/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: iVRz7qPaGZERHRitzgJ37NqRqTvOeyVNKsbtPd9rO0lhd4tbXMf1nQbI8mz5EPNkEXkSE11AnTRIyV1CBPTcxg==
 */

/* eslint-disable */
// tslint:disable

import Cities from './cities'
import Countries from './countries'
import PhoneNumbers from './phone_numbers'
import Plans from './plans'
import States from './states'

interface Users {
  address_complement: (string) | null
  address_number: (string) | null
  address_street: (string) | null
  city_id: Cities['id']
  country_id: Countries['id']
  /**
   * @default '2022-07-19'::date
   */
  created_at: Date
  document_number: string
  email: string
  first_name: string
  /**
   * @default nextval('users_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'users_id'}
  /**
   * @default true
   */
  is_active: (boolean) | null
  last_name: string
  middle_name: (string) | null
  neighbourhood: (string) | null
  password: string
  phone_number_id: (PhoneNumbers['id']) | null
  plan_id: (Plans['id']) | null
  postal_code: (string) | null
  state_id: States['id']
  /**
   * @default '2022-07-19'::date
   */
  updated_at: Date
  /**
   * @default false
   */
  was_activated: (boolean) | null
}
export default Users;

interface Users_InsertParameters {
  address_complement?: (string) | null
  address_number?: (string) | null
  address_street?: (string) | null
  city_id: Cities['id']
  country_id: Countries['id']
  /**
   * @default '2022-07-19'::date
   */
  created_at?: Date
  document_number: string
  email: string
  first_name: string
  /**
   * @default nextval('users_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'users_id'}
  /**
   * @default true
   */
  is_active?: (boolean) | null
  last_name: string
  middle_name?: (string) | null
  neighbourhood?: (string) | null
  password: string
  phone_number_id?: (PhoneNumbers['id']) | null
  plan_id?: (Plans['id']) | null
  postal_code?: (string) | null
  state_id: States['id']
  /**
   * @default '2022-07-19'::date
   */
  updated_at?: Date
  /**
   * @default false
   */
  was_activated?: (boolean) | null
}
export type {Users_InsertParameters}
